# Network:
GENESIS_TIME: 1635699600

# Chain:
CHAIN_ID: 808081
NETWORK_ID: 808081
FORK_CHOICE: 0x83a55317

# Bootnodes:
PANDORA_BOOTNODES: ""
VANGUARD_BOOTNODES: ""

# Stats pages:
ETH1_STATS_URL:
ETH1_STATS_APIKEY:
ETH2_STATS_URL:
