# The full config options can be found here:
# https://geth.ethereum.org/docs/fundamentals/config-files

[Eth]
NetworkId = 4201


[Eth.Miner]
GasCeil = 42000000
GasPrice = 1000000  # 0.001 Gwei


[Node]
DataDir = "./testnet-data/execution"
# IPCPath = "./testnet-data/execution/geth.ipc"
HTTPHost = "localhost"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth"] # ["net", "eth", "web3", "debug", "engine", "txpool"]
WSHost = "localhost"
WSPort = 8546
WSModules = ["net", "web3", "eth"]  # ["net", "eth", "web3", "debug", "engine", "txpool"]
# GraphQLVirtualHosts = ["localhost"]

# Engine API
JWTSecret = "./configs/shared/secrets/jwt.hex"
AuthAddr = "localhost"
AuthPort = 8551
AuthVirtualHosts = ["localhost"] # ["*"]


[Node.P2P]
BootstrapNodes = ["enode://c2bb19ce658cfdf1fecb45da599ee6c7bf36e5292efb3fb61303a0b2cd07f96c20ac9b376a464d687ac456675a2e4a44aec39a0509bcb4b6d8221eedec25aca2@34.141.196.212:30303","enode://d28440f93443fcfe0596502bb96fee8e0b196ff97b461a19cf0d4e482886849e72e3001dbf9a23435e136016b6c3cc09af48b93dc8b03146dc05f0fd4edb72ba@57.128.20.40:30310"]
BootstrapNodesV5 = []

StaticNodes = []
TrustedNodes = []

MaxPeers = 50
NoDiscovery = false
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false

[Ethstats]
# URL = "<NODE_NAME>:<ETH_STATS_SECRET>@stats.execution.testnet.lukso.network"
