version: "3.4"
services:

  init-geth:
    image: europe-docker.pkg.dev/lks-lz-artifacts/docker-geth/geth:$GETH_VERSION
    container_name: lukso-geth-init
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    command: >
      --datadir=/execution_data init ./configs/genesis.json

  geth:
    image: europe-docker.pkg.dev/lks-lz-artifacts/docker-geth/geth:$GETH_VERSION
    container_name: lukso-geth
    depends_on:
      - init-geth
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --datadir=/execution_data
      --ws
      --ws.api "net,eth,debug,engine"
      --nat extip:$EXTERNAL_IP
      --bootnodes $GETH_BOOTSTRAP_NODE
      --networkid $GETH_NETWORK_ID
      --http
      --http.api "net,eth,debug,engine"
      --http.addr "0.0.0.0"
      --verbosity $GETH_VERBOSITY
      --ipcdisable
      --port $GETH_PEER_PORT
      --http.port $GETH_HTTP_PORT
      --ethstats "${NODE_NAME}@${ETH_STATS_ADDRESS}"
    network_mode: host

  lighthouse_beacon:
    image: europe-docker.pkg.dev/lks-lz-artifacts/docker-lighthouse/beacon:$LH_BEACON_VERSION
    container_name: lighthouse_beacon
    depends_on:
      - geth
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --debug-level $LH_VERBOSITY
      beacon_node
      --datadir /consensus_data
      --testnet-dir /configs
      --http-allow-sync-stalled
      --merge
      --execution-endpoints http://localhost:8551
      --eth1-endpoints http://localhost:8545
      --http
      --http-allow-origin="*"
      --metrics-allow-origin="*"
      --metrics
      --jwt-secrets /execution_data/geth/jwtsecret
      --boot-nodes $CONSENSUS_BOOTSTRAP_NODE
      --suggested-fee-recipient $ETHERBASE
    network_mode: host

  lighthouse_validator:
    image: europe-docker.pkg.dev/lks-lz-artifacts/docker-lighthouse/beacon:$LH_BEACON_VERSION
    container_name: lighthouse_validator
    depends_on:
      - lighthouse_beacon
    volumes:
      - $KEYSTORE_VOLUME:/keystore
      - $VALIDATOR_DATA_VOLUME:/validator_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --debug-level $LH_VERBOSITY
      validator_client
      --datadir /validator_data
      --testnet-dir /configs
      --http
      --metrics
      --init-slashing-protection
      --beacon-nodes http://localhost:5052
      --graffiti $GRAFFITI
      --suggested-fee-recipient $ETHERBASE
    network_mode: host

  lighthouse_account:
    image: europe-docker.pkg.dev/lks-lz-artifacts/docker-lighthouse/beacon:$LH_BEACON_VERSION
    container_name: lighthouse_validator
    volumes:
      - $KEYSTORE_VOLUME:/keystore
      - $VALIDATOR_DATA_VOLUME:/validator_data
      - $CONFIGS_VOLUME:/configs
    command: >
      account validator import
      --datadir /validator_data
      --testnet-dir /configs
      --directory /keystore/keys
      --password-file /keystore/password.txt
      --reuse-password
    network_mode: host

  eth2stats-client:
    image: macht/eth2stats-client:v1.0.0
    container_name: eth2stats-client
    depends_on:
      - lighthouse_beacon
    command: >
      run
      --beacon.type=v1
      --eth2stats.node-name=$NODE_NAME
      --eth2stats.addr=$ETH_2_STATS_ADDRESS
      --eth2stats.tls=false
      --beacon.metrics-addr=http://localhost:5054/metrics
      --beacon.addr=http://localhost:5052
    network_mode: host