version: "3.4"

services:
  prysm_beacon:
    image: europe-docker.pkg.dev/lks-lz-artifacts/docker-prysm/beacon:$PRYSM_BEACON_VERSION
    container_name: prysm_beacon
    depends_on:
      - eth2stats-client
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
    env_file: ./.env
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --config-file=/configs/prysm-beacon.yml
    network_mode: host

  prysm_validator:
    image: europe-docker.pkg.dev/lks-lz-artifacts/docker-prysm/validator:$PRYSM_BEACON_VERSION
    container_name: prysm_validator
    depends_on:
      - prysm_beacon
    volumes:
      - $KEYSTORE_VOLUME:/keystore
      - $VALIDATOR_DATA_VOLUME:/validator_data
      - $CONFIGS_VOLUME:/configs
    env_file: ./.env
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --config-file=/configs/prysm-validator.yml
    network_mode: host

  eth2stats-client:
    image: macht/eth2stats-client:v1.0.0
    container_name: eth2stats-client
    restart: unless-stopped
    command: >
      run
      --beacon.type=prysm
      --eth2stats.node-name=$NODE_NAME
      --eth2stats.addr=$ETH_2_STATS_ADDRESS
      --eth2stats.tls=false
      --beacon.metrics-addr=http://127.0.0.1:8080/metrics
      --beacon.addr=127.0.0.1:4000
    network_mode: host
