network = './configs/mainnet/nimbus2'
data-dir = './mainnet-data/consensus'
el = ['http://localhost:8551'] 
jwt-secret = './configs/shared/secrets/jwt.hex'
genesis-state = './configs/mainnet/shared/genesis.ssz'
rest = true
rest-address = '127.0.0.1'
rest-port = 5052
doppelganger-detection = true
bootstrap-file = './configs/mainnet/nimbus2/bootnodes.txt'
