networkid = 3030
chain = "mainnet"

externalcl = true

datadir = "./devnet-data/execution"
"authrpc.jwtsecret" = "./configs/shared/secrets/jwt.hex"
nat = "any"
ws = true
http = true
"http.addr" = "0.0.0.0"
"http.api" = "erigon" # "eth,erigon,engine,debug,trace"
"http.vhosts" = "*"
"authrpc.addr" = "0.0.0.0"
"authrpc.port" = 8551
"authrpc.vhosts" = "*"

# ethstats = "${NODE_NAME}@${ETH_STATS_IP}"

bootnodes = []
