name: Generate config

on:
  workflow_dispatch:
    inputs:
      genesisTime:
        description: 'Genesis time'
        required: true
        default: '0'
      network:
        description: 'Network'
        required: false
        default: 'l15'
      namespace:
        description: 'Namespace'
        required: false
        default: 'dev'

jobs:
  generateConfigs:
    runs-on: ubuntu-18.04
    steps:
      - run: |
          echo "Generating config with genesis timestamp ${{ github.event.inputs.genesisTime }} for network ${{ github.event.inputs.network }}-${{ github.event.inputs.namespace }}"
          pwd
          ../updateGenesisTime.sh ${{ inputs.network }} ${{ inputs.namespace }} ${{ inputs.genesisTime }}